---
title: "Homework 10"
author: "Lindsey Pett"
date: "3/28/2018"
output: html_document
---

```{r, warning=FALSE}
# Basic code for batch processing
# 27 March 2018
# LAP

##############################################
# FUNCTION: FileBuilder
# create a set of random files for regression
# input: fileN = number of files to create
#      : fileFolder = name of folder for random files
#      : fileSize = c(min, max) number of rows in file 
#      : fileNA = number on average of NA per column
# output: set of random files
#--------------------------------------------
FileBuilder <- function(fileN=10,
                        fileFolder="RandomFiles/",
                        fileSize=c(15,100),
                        #fileSize=c(3,100)
                        fileNA=3) {
                        #fileNA=4
  for (i in seq_len(fileN)) {
  fileLength <- sample(fileSize[1]:fileSize[2],size=1)
  varX <- runif(fileLength) # random x values
  varY <- runif(fileLength) # random y values
  dF <- data.frame(varX, varY) # bind to data frame
  badVals <- rpois(n=1, lambda=fileNA) # poison for position, lambda avg number events taking place # number of NA
  dF[sample(nrow(dF),size=badVals),1] <- NA # pick subset of row give all columns      
  dF[sample(nrow(dF),size=badVals),2] <- NA
  
# create a consecturive file name for this data frame
fileLabel <- paste(fileFolder,
                   "ranFile",
                   formatC(i,
                   width=3,
                   format="d",
                   flag="0"),
                   ".csv",sep="")

# set up data file and incorporate time stamp and minimal metadata
write.table(cat("# Simulated random data file",
                "for batch processing","\n",
                "# timestamp: ",as.character(Sys.time()),"\n",
                "# LAP","\n",
                "#-----------------------","\n",
                "\n",
file=fileLabel,
row.names="",
col.names="",
sep=""))


# add the data frame now
write.table(x=dF,
            file=fileLabel,
            sep=",",
            row.names=FALSE,
            append=TRUE)
} # close the for loop
} # close the function

##############################################
# FUNCTION: regStats
# fit linear model, get regression stats
# input: 2-column data frame
# output: slope, p-value and r2
#--------------------------------------------
regStats <- function(d=NULL) {
  if(is.null(d)) {
    xVar <- runif(10)
    yVar <- runif(10)
    d <- data.frame(xVar,yVar)
  }
  . <- lm(data=d,d[,2]~d[,1])
  . <- summary(.)
  statsList <- list(Slope=.$coefficients[2,1],
                    pVal=.$coefficients[2,4],
                    r2=.$r.squared)
  return(statsList)
  
}


#---------------------------------------------------
#Start of body of program
library(TeachingDemos)
char2seed("Freezing March")
#----------------------------------------------------
# Global variables
fileFolder<-"RandomFiles/"
nFiles<-100
fileOut<-"StatsSummary.csv"

# Create 100 random data sets
FileBuilder(fileN=nFiles)
###---------------------------###
#Lab
fileNames <- list.files(path=fileFolder)
# Create data frame to hold file summary statistics
ID <- seq_along(fileNames)
fileName <- fileNames
slope <- rep(NA,nFiles)
pVal <- rep(NA,nFiles)
r2 <- rep(NA, nFiles)

statsOut<-data.frame(ID, fileName, slope, pVal, r2)

# batch process by looping through individual files
for (i in seq_along(fileNames)){
  data<-read.table(file=paste(fileFolder,fileNames[i],sep=""),
                   sep=",",
                   header=TRUE) # read in next data files
  
  dClean<-data[complete.cases(data),] # get clean cases
  
  . <- regStats(dClean) # pull regression stats from clean file
  statsOut[i,3:5]<-unlist(.) #unlist, copy intor last 3 columns
}

# set up output file and incorporate time stamp and minimal metadata
write.table(cat("# Summary stats for",
                "batch processing of regression models","\n",
                "# timestamp:", as.character(Sys.time()),"\n",
                "# LAP", "\n",
                "#---------------","\n",
                "\n",
                file=fileOut,
                row.names="",
                col.names="",
                sep=""))

# now add the data frame
write.table(x=statsOut,
            file=fileOut,
            row.names=FALSE,
            col.names=TRUE,
            sep=",",
            append=TRUE)            

```
Try “breaking” the program by decreasing the range of possible row numbers in each random file, and/or increasing the number of NA values that are randomly created (what will you have to change in the code to achieve this?). Change parameters gradually until you create a data file that cannot be fit with lm because there aren’t enough data. What happens? Does the program fail entirely or create some of the output? Are there any error messages? Be sure to delete the files within the RandomFiles folder (but do not delete the folder itself!), and also delete the StatsSummary.csv file before you run each of your “experiments”.

When trying to break the program I first changed the fileSize from the origion fileSize=c(15,100) to fileSize=c(3,100) and changed the fileNA fileNA=3 to fileNA=4. The row size is between 3 to 100, when introducing a NA value of 4 it throws an average of 4 NAs per file. If there are more NAs than there are of random rows than an error will be thrown and not all csv files will be made.
                        
